apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kuard
  name: kuard
spec:
  replicas: 10
  selector:
    matchLabels:
      run: kuard
  template:
    metadata:
      labels:
        run: kuard
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
        name: kuard
        resources:
          limits:
            cpu: 50m
            memory: 0.1G
          requests:
            cpu: 50m
            memory: 0.1G
      tolerations:
      - key: "virtual-kubelet.io/provider"
        operator: "Equal"
        value: "azure"
        effect: "NoSchedule"